apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-mysql
  namespace: uat
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mysql/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-jenkins
  namespace: uat
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/jenkins/data"
