apiVersion: v1
kind: Service
metadata:
  name: php-mysql
  namespace: cicd
  labels:
    app: php-mysql-V1.0.0
spec:
  ports:
    - port: 8080
      targetPort: 80
      name: http
  selector:
    app: php-mysql
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: php-mysql
  namespace: cicd
spec:
  selector:
    matchLabels:
      app: php-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: php-mysql
    spec:
      containers:
      - image: autherlj/mytest
        name: php-mysql
        env:
        - name: MYSQL_PORT_3306_TCP_ADDR
          value: mysql-master:3306
        - name: MYSQL_USERNAME
          value: root
        - name: MYSQL_PASSWORD
          value: P@w0rd.
        - name: MYSQL_INSTANCE_NAME
          value: homestead
        ports:
        - containerPort: 80
          name: http 
