apiVersion: v1
kind: Service
metadata:
  name: jenkins-web-ui
  namespace: uat
  labels:
    app: jenkins
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: web-ui
    - port: 50000
      targetPort: 50000
      name: agent
  selector:
    app: jenkins
    tier: jenkins
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: local-pv-jenkins
 namespace: uat
spec:
 accessModes:
    - ReadWriteOnce
 resources:
   requests:
     storage: 10Gi
 storageClassName: manual
